### ISSUE TITLE
Error when fetching HubDB table to existing dir

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#187]
If you try to fetch a Hubdb table into an existing directory (like `hs hubdb fetch 1739916 folder`), you get the error:
```
[ERROR] Error: EISDIR: illegal operation on a directory, open '/Users/wspiro/DESKTOP_TEMP/local-cms-dev/folder'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at downloadHubDbTable (/usr/local/lib/node_modules/@hubspot/cms-cli/node_modules/@hubspot/cms-lib/hubdb.js:166:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/usr/local/lib/node_modules/@hubspot/cms-cli/commands/hubdb.js:92:9) {
  errno: -21,
  syscall: 'open',
  code: 'EISDIR',
  path: '/Users/wspiro/DESKTOP_TEMP/local-cms-dev/folder'
```

**Comment by williamspiro** [comment]
We should improve the error handling here, however, my misunderstanding was that `<dest>` actually is the name of the file to be created locally.
